version: "3.2"

services:
  indexer:
    image: "samouraiwallet/dojo-indexer:${DOJO_INDEXER_VERSION_TAG}"
    container_name: indexer
    build:
      context: ./indexer
      args:
        INDEXER_LINUX_UID: ${INDEXER_LINUX_UID}
        INDEXER_LINUX_GID: ${INDEXER_LINUX_GID}
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-bitcoind.conf
      - ./conf/docker-indexer.conf
    restart: on-failure
    command: "/wait-for-it.sh tor:9050 --timeout=360 --strict -- /restart.sh"
    ports:
      - "50001:50001"
    expose:
      - "8080"
    volumes:
      - data-indexer:/home/indexer
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - tor
    networks:
      dojonet:
        ipv4_address: ${NET_DOJO_INDEXER_IPV4}

volumes:
  data-indexer:
